# This workflow is used to convert changed {community}.model.csv to {community}.model.jsonld
# and push the updated {community}.model.jsonld to feature branch

name: CI

on:
  pull_request:
    branches: main
    # change * to your data-model.csv name if needed
    paths: '**.model.csv'

jobs:
  CI:
    name: generate-jsonschema
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Generate JSON Schemas
        id: generate
        uses: Sage-Bionetworks-Actions/generate-jsonschema@main
        with:
          data-model-source: ./example.model.csv
          data-model-labels: "display_label"
