# This workflow is used to generate jsonschemas from {community}.model.csv

name: CI

on:

  pull_request:
    branches:
      - main
    # change * to your data-model.csv name if needed
    paths:
      - '**.model.csv'
      - "modules/**"

  release:
    types: [published]

  # push:
  #   branches:
  #     - "*"

jobs:

  generate-jsonschema-from-one-csv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Generate JSON Schemas
        id: generate
        uses: Sage-Bionetworks-Actions/generate-jsonschema@main
        with:
          data-model-source: ./example.model.csv
          data-model-labels: "display_label"
      - name: Upload schemas as artifacts
        uses: actions/upload-artifact@v6
        with:
          name: json-schemas
          path: "**/*.json"
          if-no-files-found: warn

  generate-jsonschema-from-multiple-csv:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Assemble CSV files
        run: |
          python scripts/assemble_csv_data_model.py ./modules/ assembled.model.csv
      - name: Generate JSON Schemas
        id: generate
        uses: Sage-Bionetworks-Actions/generate-jsonschema@main
        with:
          data-model-source: ./assembled.model.csv
          data-model-labels: "display_label"
      - name: Upload schemas and assembled model as artifacts
        uses: actions/upload-artifact@v6
        with:
          name: json-schemas-and-assembled-csv
          path: |
            **/*.json
            assembled.model.csv
          if-no-files-found: warn
      - name: Register schemas in Synapse (without version)
        if: github.event_name != 'release'
        id: register
        uses: Sage-Bionetworks-Actions/register-jsonschema@develop
        with:
          org-name: dpetest
          schema-dir: ${{ steps.generate.outputs.schemas }}
          synapse-auth-token: ${{ secrets.SYNAPSE_AUTH_TOKEN }}
      - name: Register schemas in Synapse (with version)
        if: github.event_name == 'release'
        id: register-release
        uses: Sage-Bionetworks-Actions/register-jsonschema@develop
        with:
          org-name: dpetest
          schema-dir: ${{ steps.generate.outputs.schemas }}
          synapse-auth-token: ${{ secrets.SYNAPSE_AUTH_TOKEN }}
          version: ${{ github.event.release.tag_name }}
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.event.release.tag_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            **/*.json
            assembled.model.csv
