name: Create DCA Template Config File
on:
  repository_dispatch:
    types: generate_templates
  workflow_dispatch:
    inputs:
      data_model:
        description: URL to a jsonld data model file
        required: true
      path:
        description: Directory to save the template config
        required: true
        
jobs:
  create-template-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Create config file
        run: |
          install.packages("remotes")
          remotes::install_github("Sage-Bionetworks/data_curator@rc.23.11.1", auth_token = "${{ github.token }}" )
          datacurator::write_dca_template_config( "${{ inputs.data_model }}", "${{ inputs.path }}")
        shell: Rscript {0}
        
      - name: Checkout DCA Config Repo for Schema
        uses: actions/checkout@v4
        with:
          repository: 'Sage-Bionetworks/data_curator_config'
          ref: 'dev'
          path: 'data_curator_config'
        
      - name: Validate Config File
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: 'data_curator_config/schemas/dca_template_config.schema.json'
          INPUT_JSONS: ${{ inputs.path }}
      
      - name: Open PR
        uses: peter-evans/create-pull-request@v5
        with:
          title: Update DCA Template Config File
          body: Recreate the json file that populates the DCA template dropdown menu.
          delete-branch: true
          branch-suffix: timestamp
          add-paths: |
            ${{ inputs.path }}
